import React from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, Radio, Network, Shield, Wifi, Lock, Server, Database, Satellite } from 'lucide-react'
import { apiGet } from '../shared/api'
import '../styles.css'
function Panel({title, icon, children}: {title: string, icon?: React.ReactNode, children: React.ReactNode}) { return <section className="panel"><div className="panel-h">{icon}{title}</div><div className="panel-b">{children}</div></section> }
function App() {
  const [data, setData] = React.useState<any>({}); const [err, setErr] = React.useState<string>('')
  React.useEffect(()=>{ async function load(){ try { const keys:[string,string][]=[['health','/health'],['mission','/mission/status'],['events','/events/demo'],['plane','/scientific/plane-wave/demo'],['network','/network-fabric/path?destination=New%20York'],['mns','/telco-mns/status'],['assets','/assets/demo'],['rat','/access-trust/rat/demo'],['wifi','/access-trust/wifi/demo'],['soc','/soc-noc/correlation/demo'],['restricted','/restricted/status']]; const results:any={}; for (const [k,p] of keys) results[k]=await apiGet<any>(p); setData(results) } catch(e:any){ setErr(String(e)) }} load() }, [])
  return <main className="shell"><header className="top"><div><h1>TELCO RF MISSION CONTROL PLATFORM</h1><p>Full Telco Skeleton · Mission Orchestrator · CloudEvents · RF/EM/DSP · GWAN · Access Trust</p></div><div className="badge">v0.2 · {data.health?.operational_mode ?? 'BOOT'}</div></header><section className="layout"><aside className="nav">{['Mission','CloudEvents','Scientific Core','Global Network','Telco MnS','Assets','RAT Defense','Wi-Fi Trust','SOC/NOC','Evidence','Restricted'].map(x=><div className="navitem" key={x}>{x}</div>)}</aside><section className="main">{err && <div className="error">{err}</div>}<Panel title="Mission Orchestrator" icon={<Activity/>}><pre>{JSON.stringify(data.mission,null,2)}</pre></Panel><div className="grid2"><Panel title="Scientific RF/EM Core" icon={<Radio/>}><div className="metric">f: {fmt(data.plane?.frequency_hz)} Hz</div><div className="metric">λ: {sci(data.plane?.wavelength_m)} m</div><div className="metric">η: {sci(data.plane?.intrinsic_impedance_ohm)} Ω</div><div className="metric">S: {sci(data.plane?.poynting_w_per_m2)} W/m²</div><div className="emview"><span>E</span><span>H</span><span>k</span></div></Panel><Panel title="Global Network Journey" icon={<Network/>}><div className="path">{data.network?.segments?.map((s:any)=><div className="hop" key={s.segment_id}><b>{s.type}</b><span>{s.latency_ms} ms</span></div>)}</div><div className="metric">RTT: {data.network?.estimated_rtt_ms} ms · MOS {data.network?.mos_estimate}</div></Panel></div><Panel title="Telco MnS / 3GPP OAM Predisposition" icon={<Server/>}><pre>{JSON.stringify(data.mns,null,2)}</pre></Panel><Panel title="Event Fabric — CloudEvents demo" icon={<Database/>}><pre>{JSON.stringify(data.events,null,2)}</pre></Panel></section><aside className="context"><Panel title="RAT Downgrade Defense" icon={<Shield/>}><div className="risk high">{data.rat?.classification}</div><pre>{JSON.stringify(data.rat,null,2)}</pre></Panel><Panel title="Wi-Fi Trust Defense" icon={<Wifi/>}><div className="risk critical">{data.wifi?.classification}</div><pre>{JSON.stringify(data.wifi,null,2)}</pre></Panel><Panel title="SOC/NOC Correlation" icon={<Satellite/>}><pre>{JSON.stringify(data.soc,null,2)}</pre></Panel><Panel title="Restricted Intelligence" icon={<Lock/>}><div className="locked">LOCKED</div><pre>{JSON.stringify(data.restricted,null,2)}</pre></Panel></aside></section><footer className="timeline">GLOBAL TIME CURSOR · waveform · spectrum · protocol · logs · KPI · evidence · network path</footer></main>
}
function fmt(v:any){ return v===undefined?'—':Number(v).toLocaleString('it-IT') } function sci(v:any){ return v===undefined?'—':Number(v).toExponential(3) }
createRoot(document.getElementById('root')!).render(<App />)
