export type NavigationStatusV39 = 'ready' | 'partial' | 'planned'

export type NavigationDomainV39 = {
  id: string
  title: string
  subtitle: string
  status: NavigationStatusV39
  priority: number
  domain: string
  routeHint: string
  liveEndpoint?: string
  anchors: string[]
  capabilities: string[]
  nextStep: string
}

export const navigationDomainsV39: NavigationDomainV39[] = [
  {
    id: 'mission-control',
    title: 'Mission Control',
    subtitle: 'Command Center, runtime status, health, read-only source and portal governance.',
    status: 'ready',
    priority: 1,
    domain: 'mission',
    routeHint: 'V37 Command Center Fusion',
    liveEndpoint: '/api/mission/status',
    anchors: ['CommandCenterFusionV37', 'V37', 'V38 design system'],
    capabilities: ['global readiness', 'live API source', 'safe entrypoint fusion'],
    nextStep: 'Use as top-level operational dashboard.',
  },
  {
    id: 'rf-physics',
    title: 'RF Physics',
    subtitle: 'Maxwell, propagation, fields, spectrum concepts, RF theory and scenario links.',
    status: 'ready',
    priority: 2,
    domain: 'rf',
    routeHint: '02_RF_Physics',
    anchors: ['RF Physics', 'Maxwell', 'V36 physics overlay'],
    capabilities: ['theory layer', 'field visualization', 'scenario binding'],
    nextStep: 'Bind formulas and theory cards to V36 scenarios.',
  },
  {
    id: 'signal-analyzer',
    title: 'Signal Analyzer',
    subtitle: 'Spectrum, waterfall, IQ, markers, DSP worker and instrument workbench.',
    status: 'ready',
    priority: 2,
    domain: 'rf',
    routeHint: '03_Signal_Analyzer',
    liveEndpoint: '/api/rfpro/spectrum/sweep',
    anchors: ['Spectrum', 'Waterfall', 'IQ', 'RFInstrument'],
    capabilities: ['spectrum contract', 'waterfall', 'IQ pipeline', 'measurement UX'],
    nextStep: 'Unify RF instrument deck with Navigation Map domain.',
  },
  {
    id: 'rf-microwave-engineering',
    title: 'RF / Microwave Engineering',
    subtitle: 'Smith chart, S-parameters, VNA, microwave components and lab procedures.',
    status: 'ready',
    priority: 3,
    domain: 'rf-lab',
    routeHint: '04_RF_Microwave_Engineering',
    anchors: ['microwave', 'Smith', 'S-parameters', 'VNA'],
    capabilities: ['measurement theory', 'lab workflow', 'instrument correlation'],
    nextStep: 'Add Smith/S-parameter knowledge cards.',
  },
  {
    id: 'antenna-system',
    title: 'Antenna System',
    subtitle: 'Antenna families, microstrip, tower systems, beamwidth and coverage.',
    status: 'ready',
    priority: 2,
    domain: 'antenna',
    routeHint: '05_Antenna_System',
    liveEndpoint: '/api/rfpro/bandplan',
    anchors: ['Antenna', 'microstrip', 'beamwidth', 'tower'],
    capabilities: ['antenna taxonomy', 'pattern context', 'coverage scenarios'],
    nextStep: 'Connect visual render assets to V36 antenna scenes.',
  },
  {
    id: 'microwave-link',
    title: 'Microwave Link',
    subtitle: 'Backhaul, dish links, link budget, fade margin and point-to-point systems.',
    status: 'ready',
    priority: 4,
    domain: 'transport',
    routeHint: '06_Microwave_Link',
    anchors: ['link budget', 'microwave', 'dish', 'backhaul'],
    capabilities: ['link budget', 'backhaul topology', 'coverage tradeoff'],
    nextStep: 'Create link-budget calculator/read-only scenario.',
  },
  {
    id: 'fiber-optic',
    title: 'Fiber Optic',
    subtitle: 'Optical transport, fiber plant, backbone links and physical connectivity.',
    status: 'partial',
    priority: 4,
    domain: 'transport',
    routeHint: '07_Fiber_Optic',
    anchors: ['fiber'],
    capabilities: ['fiber context placeholder', 'transport knowledge'],
    nextStep: 'Expand with fiber topology, OTDR, splice and transport cards.',
  },
  {
    id: 'private-networks',
    title: 'Private Networks',
    subtitle: 'Private 5G, enterprise deployments, network slicing context and lab topology.',
    status: 'ready',
    priority: 3,
    domain: '5g',
    routeHint: '08_Private_Networks',
    anchors: ['private', '5g', 'network'],
    capabilities: ['private 5G architecture', 'lab topology', 'enterprise scenarios'],
    nextStep: 'Bind to Open5GS/UERANSIM state and topology map.',
  },
  {
    id: 'core-network',
    title: 'Core Network',
    subtitle: 'Open5GS, AMF, SMF, UPF, AUSF, UDM, NAS, PFCP and GTP-U.',
    status: 'ready',
    priority: 2,
    domain: '5g-core',
    routeHint: '09_Core_Network',
    liveEndpoint: '/api/core/open5gs/status',
    anchors: ['Open5GS', 'core/open5gs', 'AMF'],
    capabilities: ['core readiness', '5G call-flow context', 'identity/security model'],
    nextStep: 'Connect SUPI/SUCI, AKA, NAS and PDU session visual flows.',
  },
  {
    id: 'data-center-infrastructure',
    title: 'Data Center Infrastructure',
    subtitle: 'Compute, infrastructure, server/runtime services and future telco cloud mapping.',
    status: 'ready',
    priority: 4,
    domain: 'infrastructure',
    routeHint: '10_Data_Center_Infrastructure',
    anchors: ['data center', 'infrastructure'],
    capabilities: ['infrastructure context', 'runtime services', 'future telco cloud'],
    nextStep: 'Map backend/frontend/proxy/systemd services into topology.',
  },
  {
    id: 'cyber-rf-intelligence',
    title: 'Cyber RF Intelligence',
    subtitle: 'SOC/NOC correlation, RF/cyber event context, evidence and safe read-only analysis.',
    status: 'ready',
    priority: 3,
    domain: 'cyber',
    routeHint: '11_Cyber_RF_Intelligence',
    liveEndpoint: '/api/soc-noc/correlation/demo',
    anchors: ['SOC', 'NOC', 'correlation', 'cyber'],
    capabilities: ['correlation contract', 'evidence view', 'RF/cyber awareness'],
    nextStep: 'Create event timeline and evidence binding.',
  },
  {
    id: 'knowledge-base',
    title: 'Knowledge Base',
    subtitle: 'Glossary, theory, assets, visual references, teaching and engineering documentation.',
    status: 'partial',
    priority: 3,
    domain: 'knowledge',
    routeHint: '12_Knowledge_Base',
    anchors: ['Knowledge', 'visual assets'],
    capabilities: ['knowledge index', 'visual context', 'training library'],
    nextStep: 'Bind scenarios to formulas, visuals and glossary pages.',
  },
]

export const navigationMetaV39 = {
  title: 'TRFMC V39 Navigation Architecture',
  subtitle: 'Official mission/domain map above the V37 Command Center.',
  readyCount: 10,
  partialCount: 2,
  missingCount: 0,
  source: 'V39A inventory audit',
}
