export type WorkingPage = {
  status: string
  category: string
  title: string
  url: string
  file: string
  domCanvas: number
  sourceCanvas: number
  rfHits: number
  scriptTags: number
  rootLinks: number
}

export const workingPages: WorkingPage[] = 
[
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC Domain Registry V1",
    "url": "/trfmc_domain_registry_v1.html",
    "file": "frontend/public/trfmc_domain_registry_v1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 144,
    "scriptTags": 5,
    "rootLinks": 98
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.82A · Native WebGL RF Vegetation Lab",
    "url": "/webgl_rf_heatmap_engine_v82_native_lab.html",
    "file": "frontend/public/webgl_rf_heatmap_engine_v82_native_lab.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 20,
    "scriptTags": 6,
    "rootLinks": 13
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.70A Unified Shell · TRFMC v0.66A · WebGL RF Heatmap Engine",
    "url": "/webgl_rf_heatmap_engine_v66.html",
    "file": "frontend/public/webgl_rf_heatmap_engine_v66.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 19,
    "scriptTags": 7,
    "rootLinks": 15
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.83D · Instrument Layout + Link Budget Inspector",
    "url": "/webgl_rf_physics_engine_v83d.html",
    "file": "frontend/public/webgl_rf_physics_engine_v83d.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 17,
    "scriptTags": 7,
    "rootLinks": 19
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.83E · Instrument Readability + Vector Governance",
    "url": "/webgl_rf_physics_engine_v83e.html",
    "file": "frontend/public/webgl_rf_physics_engine_v83e.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 17,
    "scriptTags": 8,
    "rootLinks": 21
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.83F · Dual Instrument View + RSRP/SINR Profile",
    "url": "/webgl_rf_physics_engine_v83f.html",
    "file": "frontend/public/webgl_rf_physics_engine_v83f.html",
    "domCanvas": 4,
    "sourceCanvas": 2,
    "rfHits": 17,
    "scriptTags": 9,
    "rootLinks": 23
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.85B · Sapienza Physics Baseline + RSRP/SINR Profile",
    "url": "/webgl_rf_physics_engine_v85b_sapienza_baseline.html",
    "file": "frontend/public/webgl_rf_physics_engine_v85b_sapienza_baseline.html",
    "domCanvas": 4,
    "sourceCanvas": 2,
    "rfHits": 17,
    "scriptTags": 10,
    "rootLinks": 24
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.85C · Sapienza Physics Baseline + RSRP/SINR Profile",
    "url": "/webgl_rf_physics_engine_v85c_sapienza_identity.html",
    "file": "frontend/public/webgl_rf_physics_engine_v85c_sapienza_identity.html",
    "domCanvas": 4,
    "sourceCanvas": 2,
    "rfHits": 17,
    "scriptTags": 11,
    "rootLinks": 25
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.85D · Sapienza Physics Baseline + RSRP/SINR Profile",
    "url": "/webgl_rf_physics_engine_v85d_runtime_identity_lock.html",
    "file": "frontend/public/webgl_rf_physics_engine_v85d_runtime_identity_lock.html",
    "domCanvas": 4,
    "sourceCanvas": 2,
    "rfHits": 17,
    "scriptTags": 12,
    "rootLinks": 26
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.85E · Sapienza Physics Baseline + RSRP/SINR Profile",
    "url": "/webgl_rf_physics_engine_v85e_viewport_discipline.html",
    "file": "frontend/public/webgl_rf_physics_engine_v85e_viewport_discipline.html",
    "domCanvas": 4,
    "sourceCanvas": 2,
    "rfHits": 17,
    "scriptTags": 12,
    "rootLinks": 26
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.70A Unified Shell · TRFMC v0.67A · Urban Shadowing & Clutter Engine",
    "url": "/webgl_rf_heatmap_engine_v67.html",
    "file": "frontend/public/webgl_rf_heatmap_engine_v67.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 14,
    "scriptTags": 7,
    "rootLinks": 16
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.81C-R2 · Seasonal Vegetation Clutter Engine · Cinematic Surgical Rebuild",
    "url": "/webgl_rf_heatmap_engine_v68_surgical_v81.html",
    "file": "frontend/public/webgl_rf_heatmap_engine_v68_surgical_v81.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 14,
    "scriptTags": 8,
    "rootLinks": 15
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.70A Unified Shell · TRFMC v0.68A · Seasonal Vegetation Clutter Engine",
    "url": "/webgl_rf_heatmap_engine_v68.html",
    "file": "frontend/public/webgl_rf_heatmap_engine_v68.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 13,
    "scriptTags": 7,
    "rootLinks": 16
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.70A Unified Shell · TRFMC v0.69A · UE Mobility & Handover Dynamics",
    "url": "/webgl_rf_heatmap_engine_v69.html",
    "file": "frontend/public/webgl_rf_heatmap_engine_v69.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 13,
    "scriptTags": 8,
    "rootLinks": 17
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.86B · Performance GPU Binding Gate",
    "url": "/trfmc_performance_gpu_gate_v86b.html",
    "file": "frontend/public/trfmc_performance_gpu_gate_v86b.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 9,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.86B-R1 · Performance GPU Binding Gate R1",
    "url": "/trfmc_performance_gpu_gate_v86b_r1.html",
    "file": "frontend/public/trfmc_performance_gpu_gate_v86b_r1.html",
    "domCanvas": 3,
    "sourceCanvas": 3,
    "rfHits": 9,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.86C · Portal Registry Navigation Spine",
    "url": "/trfmc_portal_registry_v86c.html",
    "file": "frontend/public/trfmc_portal_registry_v86c.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 9,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.87A · First Promotion Batch",
    "url": "/trfmc_first_promotion_batch_v87a.html",
    "file": "frontend/public/trfmc_first_promotion_batch_v87a.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 9,
    "scriptTags": 6,
    "rootLinks": 12
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.86C-R1 · Portal Registry Navigation Spine R1",
    "url": "/trfmc_portal_registry_v86c_r1.html",
    "file": "frontend/public/trfmc_portal_registry_v86c_r1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 3,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "Data Center / Power / PDU Infrastructure Lab",
    "url": "/trfmc_datacenter_power_pdu_infrastructure_v1.html",
    "file": "frontend/public/trfmc_datacenter_power_pdu_infrastructure_v1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 2,
    "scriptTags": 4,
    "rootLinks": 8
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "TRFMC v0.71A · Page-by-Page Visual QA Matrix",
    "url": "/trfmc_visual_qa_matrix_v71.html",
    "file": "frontend/public/trfmc_visual_qa_matrix_v71.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 1,
    "scriptTags": 7,
    "rootLinks": 13
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "3d-visual",
    "title": "Private Networks / Wi-Fi 7 / 5G Mesh Lab",
    "url": "/trfmc_private_networks_wifi7_5g_mesh_v1.html",
    "file": "frontend/public/trfmc_private_networks_wifi7_5g_mesh_v1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 0,
    "scriptTags": 4,
    "rootLinks": 8
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "5g-core-ran",
    "title": "TRFMC Engine Promotion Board V1",
    "url": "/trfmc_engine_promotion_board_v1.html",
    "file": "frontend/public/trfmc_engine_promotion_board_v1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 62,
    "scriptTags": 5,
    "rootLinks": 69
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "5g-core-ran",
    "title": "TRFMC Perfection Authority V2 Scoped",
    "url": "/trfmc_perfection_authority_v2_scoped.html",
    "file": "frontend/public/trfmc_perfection_authority_v2_scoped.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 51,
    "scriptTags": 3,
    "rootLinks": 129
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "5g-core-ran",
    "title": "TRFMC v0.35 RF/Telco Mission Portal",
    "url": "/rf_telco_mission_portal_v35.html",
    "file": "frontend/public/rf_telco_mission_portal_v35.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 27,
    "scriptTags": 7,
    "rootLinks": 20
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "5g-core-ran",
    "title": "TRFMC RF Microwave Engineering",
    "url": "/trfmc_rf_microwave_engineering.html",
    "file": "frontend/public/trfmc_rf_microwave_engineering.html",
    "domCanvas": 2,
    "sourceCanvas": 1,
    "rfHits": 3,
    "scriptTags": 5,
    "rootLinks": 7
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC Canonical Navigation Map V1",
    "url": "/trfmc_canonical_navigation_map_v1.html",
    "file": "frontend/public/trfmc_canonical_navigation_map_v1.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 202,
    "scriptTags": 3,
    "rootLinks": 139
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC Perfection Authority V3 Scoped",
    "url": "/trfmc_perfection_authority_v3_scoped.html",
    "file": "frontend/public/trfmc_perfection_authority_v3_scoped.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 200,
    "scriptTags": 3,
    "rootLinks": 129
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC Final Promotion Gate V1",
    "url": "/trfmc_final_promotion_gate_v1.html",
    "file": "frontend/public/trfmc_final_promotion_gate_v1.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 73,
    "scriptTags": 3,
    "rootLinks": 48
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC Antenna System Explorer V1.2 Operativo",
    "url": "/trfmc_antenna_system_explorer_v12_operativo.html",
    "file": "frontend/public/trfmc_antenna_system_explorer_v12_operativo.html",
    "domCanvas": 6,
    "sourceCanvas": 6,
    "rfHits": 26,
    "scriptTags": 6,
    "rootLinks": 12
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC Antenna System Explorer V1.3 Premium",
    "url": "/trfmc_antenna_system_explorer_v13_premium.html",
    "file": "frontend/public/trfmc_antenna_system_explorer_v13_premium.html",
    "domCanvas": 6,
    "sourceCanvas": 6,
    "rfHits": 26,
    "scriptTags": 6,
    "rootLinks": 12
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.82B · Native WebGL RF Field Refinement",
    "url": "/webgl_rf_heatmap_engine_v82b_native_lab.html",
    "file": "frontend/public/webgl_rf_heatmap_engine_v82b_native_lab.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 22,
    "scriptTags": 6,
    "rootLinks": 14
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.83A · RF Physics Calibrated 4D Engine",
    "url": "/webgl_rf_physics_engine_v83.html",
    "file": "frontend/public/webgl_rf_physics_engine_v83.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 21,
    "scriptTags": 6,
    "rootLinks": 15
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.83B · RF Precision Scale + Probe Diagnostics",
    "url": "/webgl_rf_physics_engine_v83b.html",
    "file": "frontend/public/webgl_rf_physics_engine_v83b.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 21,
    "scriptTags": 6,
    "rootLinks": 16
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.83C · RF Sanity Calibration + SINR-Aware Coverage",
    "url": "/webgl_rf_physics_engine_v83c.html",
    "file": "frontend/public/webgl_rf_physics_engine_v83c.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 21,
    "scriptTags": 6,
    "rootLinks": 17
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.70A Unified Shell · TRFMC v0.63B · Infrastructure Digital Twin Visual Upgrade",
    "url": "/infrastructure_digital_twin_v63.html",
    "file": "frontend/public/infrastructure_digital_twin_v63.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 18,
    "scriptTags": 4,
    "rootLinks": 10
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.82C · Native WebGL Mission Replay",
    "url": "/webgl_rf_heatmap_engine_v82c_mission_replay.html",
    "file": "frontend/public/webgl_rf_heatmap_engine_v82c_mission_replay.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 18,
    "scriptTags": 7,
    "rootLinks": 16
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.82C-R2 · Native WebGL Mission Replay Layout Fix",
    "url": "/webgl_rf_heatmap_engine_v82c_r2_mission_replay.html",
    "file": "frontend/public/webgl_rf_heatmap_engine_v82c_r2_mission_replay.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 18,
    "scriptTags": 8,
    "rootLinks": 18
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.87B · Mission Control Home",
    "url": "/trfmc_mission_control_home_v87b.html",
    "file": "frontend/public/trfmc_mission_control_home_v87b.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 16,
    "scriptTags": 6,
    "rootLinks": 15
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC Expansion Hub V1",
    "url": "/trfmc_expansion_hub_v1.html",
    "file": "frontend/public/trfmc_expansion_hub_v1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 12,
    "scriptTags": 1,
    "rootLinks": 12
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.87D · Cinematic Command Deck",
    "url": "/trfmc_cinematic_command_deck_v87d.html",
    "file": "frontend/public/trfmc_cinematic_command_deck_v87d.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 11,
    "scriptTags": 6,
    "rootLinks": 15
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.87E-R3 · Home Promotion Gate",
    "url": "/trfmc_home_v87e.html",
    "file": "frontend/public/trfmc_home_v87e.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 11,
    "scriptTags": 6,
    "rootLinks": 15
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.70A Unified Shell · TRFMC v0.65B · Field Telemetry on GPU Runtime",
    "url": "/field_engineering_mode_v64.html",
    "file": "frontend/public/field_engineering_mode_v64.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 10,
    "scriptTags": 3,
    "rootLinks": 12
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.87C · Cinematic Mission Atlas",
    "url": "/trfmc_cinematic_mission_atlas_v87c.html",
    "file": "frontend/public/trfmc_cinematic_mission_atlas_v87c.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 10,
    "scriptTags": 6,
    "rootLinks": 15
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.87F · Route Normalizer",
    "url": "/trfmc_route_normalizer_v87f.html",
    "file": "frontend/public/trfmc_route_normalizer_v87f.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 10,
    "scriptTags": 6,
    "rootLinks": 16
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC Soul Runtime Lab V1",
    "url": "/trfmc_soul_runtime_lab_v1.html",
    "file": "frontend/public/trfmc_soul_runtime_lab_v1.html",
    "domCanvas": 2,
    "sourceCanvas": 1,
    "rfHits": 5,
    "scriptTags": 4,
    "rootLinks": 10
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v0.86D-R1 · No-IFrame Route Console",
    "url": "/trfmc_unified_shell_noiframe_v86d_r1.html",
    "file": "frontend/public/trfmc_unified_shell_noiframe_v86d_r1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 5,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC v86D Quarantine · Route Locked",
    "url": "/trfmc_unified_shell_prototype_v86d.html",
    "file": "frontend/public/trfmc_unified_shell_prototype_v86d.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 5,
    "scriptTags": 5,
    "rootLinks": 10
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC Emergency Reset Layout State",
    "url": "/trfmc_emergency_reset_layout_state.html",
    "file": "frontend/public/trfmc_emergency_reset_layout_state.html",
    "domCanvas": 12,
    "sourceCanvas": 0,
    "rfHits": 3,
    "scriptTags": 1,
    "rootLinks": 1
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC Post-Promotion Control Center V1",
    "url": "/trfmc_post_promotion_control_center_v1.html",
    "file": "frontend/public/trfmc_post_promotion_control_center_v1.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 2,
    "scriptTags": 3,
    "rootLinks": 10
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "Microwave Link Operations Center",
    "url": "/trfmc_microwave_link_operations_center_v1.html",
    "file": "frontend/public/trfmc_microwave_link_operations_center_v1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 1,
    "scriptTags": 4,
    "rootLinks": 8
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC Reset Browser State V6R1",
    "url": "/trfmc_reset_browser_state_v6r1.html",
    "file": "frontend/public/trfmc_reset_browser_state_v6r1.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 1,
    "scriptTags": 1,
    "rootLinks": 2
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "antenna-rf",
    "title": "TRFMC Change Control Policy V1",
    "url": "/trfmc_change_control_policy_v1.html",
    "file": "frontend/public/trfmc_change_control_policy_v1.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 0,
    "scriptTags": 3,
    "rootLinks": 10
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC Enterprise Prime Portal V1",
    "url": "/trfmc_enterprise_prime_portal_v1.html",
    "file": "frontend/public/trfmc_enterprise_prime_portal_v1.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 92,
    "scriptTags": 6,
    "rootLinks": 37
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC RF Spectrum Lab V1",
    "url": "/trfmc_rf_spectrum_lab_v1.html",
    "file": "frontend/public/trfmc_rf_spectrum_lab_v1.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 69,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC Signal World Engine V2",
    "url": "/trfmc_signal_world_engine_v2.html",
    "file": "frontend/public/trfmc_signal_world_engine_v2.html",
    "domCanvas": 6,
    "sourceCanvas": 6,
    "rfHits": 65,
    "scriptTags": 6,
    "rootLinks": 13
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC RF/TM Signal Universe V3",
    "url": "/trfmc_rf_tm_signal_universe_v3.html",
    "file": "frontend/public/trfmc_rf_tm_signal_universe_v3.html",
    "domCanvas": 8,
    "sourceCanvas": 8,
    "rfHits": 53,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC Orphan Consolidation Dossier V1",
    "url": "/trfmc_orphan_consolidation_dossier_v1.html",
    "file": "frontend/public/trfmc_orphan_consolidation_dossier_v1.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 52,
    "scriptTags": 3,
    "rootLinks": 38
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.70A Unified Shell · TRFMC v0.60A · RF/Telco Knowledge Operating System",
    "url": "/rf_telco_knowledge_os_v60.html",
    "file": "frontend/public/rf_telco_knowledge_os_v60.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 37,
    "scriptTags": 7,
    "rootLinks": 18
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC PR200 Style Field Monitoring Receiver V1",
    "url": "/trfmc_pr200_field_monitoring_receiver_v1.html",
    "file": "frontend/public/trfmc_pr200_field_monitoring_receiver_v1.html",
    "domCanvas": 6,
    "sourceCanvas": 6,
    "rfHits": 35,
    "scriptTags": 6,
    "rootLinks": 13
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC Measurement Chain DSP Engine V2",
    "url": "/trfmc_measurement_chain_dsp_engine_v2.html",
    "file": "frontend/public/trfmc_measurement_chain_dsp_engine_v2.html",
    "domCanvas": 6,
    "sourceCanvas": 6,
    "rfHits": 32,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC Wi-Fi 5/6/7/8 OFDM QAM Engine V1",
    "url": "/trfmc_wifi_5_6_7_8_qam_engine_v1.html",
    "file": "frontend/public/trfmc_wifi_5_6_7_8_qam_engine_v1.html",
    "domCanvas": 6,
    "sourceCanvas": 6,
    "rfHits": 29,
    "scriptTags": 6,
    "rootLinks": 10
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.70A Unified Shell · TRFMC v0.61A · RF/Telco Knowledge Modules",
    "url": "/rf_telco_knowledge_modules_v61.html",
    "file": "frontend/public/rf_telco_knowledge_modules_v61.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 29,
    "scriptTags": 6,
    "rootLinks": 15
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84A · RF T&M Supreme Console",
    "url": "/webgl_rf_tm_supreme_console_v84a.html",
    "file": "frontend/public/webgl_rf_tm_supreme_console_v84a.html",
    "domCanvas": 6,
    "sourceCanvas": 6,
    "rfHits": 25,
    "scriptTags": 6,
    "rootLinks": 12
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84L · RF Sapienza Director Cockpit",
    "url": "/rf_sapienza_console_v84l.html",
    "file": "frontend/public/rf_sapienza_console_v84l.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 24,
    "scriptTags": 9,
    "rootLinks": 23
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84G · RF Topographic Instrument View",
    "url": "/rf_sapienza_console_v84g.html",
    "file": "frontend/public/rf_sapienza_console_v84g.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 23,
    "scriptTags": 6,
    "rootLinks": 15
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84I · RF Vector Cartography Console",
    "url": "/rf_sapienza_console_v84i.html",
    "file": "frontend/public/rf_sapienza_console_v84i.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 23,
    "scriptTags": 6,
    "rootLinks": 17
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84B · RF Sapienza Console",
    "url": "/rf_sapienza_console_v84b.html",
    "file": "frontend/public/rf_sapienza_console_v84b.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 22,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84C · RF Sapienza Console R2 R2",
    "url": "/rf_sapienza_console_v84c.html",
    "file": "frontend/public/rf_sapienza_console_v84c.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 22,
    "scriptTags": 6,
    "rootLinks": 12
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84D · RF Sapienza Truth Palette R2",
    "url": "/rf_sapienza_console_v84d.html",
    "file": "frontend/public/rf_sapienza_console_v84d.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 22,
    "scriptTags": 6,
    "rootLinks": 13
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84E · RF Sapienza Instrument Truth View",
    "url": "/rf_sapienza_console_v84e.html",
    "file": "frontend/public/rf_sapienza_console_v84e.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 22,
    "scriptTags": 6,
    "rootLinks": 13
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84F · RF Instrument Dark Field Discipline",
    "url": "/rf_sapienza_console_v84f.html",
    "file": "frontend/public/rf_sapienza_console_v84f.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 22,
    "scriptTags": 6,
    "rootLinks": 14
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84H · RF Atlas Instrument View",
    "url": "/rf_sapienza_console_v84h.html",
    "file": "frontend/public/rf_sapienza_console_v84h.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 22,
    "scriptTags": 6,
    "rootLinks": 16
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84J · RF 4D Measurement Theater",
    "url": "/rf_sapienza_console_v84j.html",
    "file": "frontend/public/rf_sapienza_console_v84j.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 22,
    "scriptTags": 7,
    "rootLinks": 19
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84K · RF Sapienza Layer Director",
    "url": "/rf_sapienza_console_v84k.html",
    "file": "frontend/public/rf_sapienza_console_v84k.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 22,
    "scriptTags": 8,
    "rootLinks": 21
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.84M · RF Sapienza Production Baseline",
    "url": "/rf_sapienza_console_v84m.html",
    "file": "frontend/public/rf_sapienza_console_v84m.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 22,
    "scriptTags": 10,
    "rootLinks": 25
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC Antenna System Explorer V1",
    "url": "/trfmc_antenna_system_explorer_v1.html",
    "file": "frontend/public/trfmc_antenna_system_explorer_v1.html",
    "domCanvas": 6,
    "sourceCanvas": 6,
    "rfHits": 20,
    "scriptTags": 6,
    "rootLinks": 12
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC RF Physics Theory Atlas V2",
    "url": "/trfmc_rf_physics_theory_atlas_v2.html",
    "file": "frontend/public/trfmc_rf_physics_theory_atlas_v2.html",
    "domCanvas": 3,
    "sourceCanvas": 3,
    "rfHits": 20,
    "scriptTags": 4,
    "rootLinks": 8
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.70A Unified Shell · TRFMC v0.62B · RF Propagation Sandbox Visual Upgrade",
    "url": "/rf_propagation_sandbox_v62.html",
    "file": "frontend/public/rf_propagation_sandbox_v62.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 19,
    "scriptTags": 8,
    "rootLinks": 15
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.87G · Public Operational Home",
    "url": "/trfmc_home.html",
    "file": "frontend/public/trfmc_home.html",
    "domCanvas": 3,
    "sourceCanvas": 3,
    "rfHits": 16,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.87G · Public Operational Home",
    "url": "/trfmc_home_v87g.html",
    "file": "frontend/public/trfmc_home_v87g.html",
    "domCanvas": 3,
    "sourceCanvas": 3,
    "rfHits": 16,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.86F · Design Token Audit",
    "url": "/trfmc_design_token_audit_v86f.html",
    "file": "frontend/public/trfmc_design_token_audit_v86f.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 10,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "Antenna / RRU / RET / CPRI Port Mapping Simulator",
    "url": "/trfmc_antenna_rru_ret_cpri_port_mapping_v1.html",
    "file": "frontend/public/trfmc_antenna_rru_ret_cpri_port_mapping_v1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 9,
    "scriptTags": 4,
    "rootLinks": 8
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.87G · Public Operational Home",
    "url": "/trfmc.html",
    "file": "frontend/public/trfmc.html",
    "domCanvas": 3,
    "sourceCanvas": 3,
    "rfHits": 9,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "RF Physics Theory Atlas",
    "url": "/trfmc_rf_physics_theory_atlas_v1.html",
    "file": "frontend/public/trfmc_rf_physics_theory_atlas_v1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 5,
    "scriptTags": 4,
    "rootLinks": 8
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC True Portal Command Deck V1",
    "url": "/trfmc_true_portal_command_deck_v1.html",
    "file": "frontend/public/trfmc_true_portal_command_deck_v1.html",
    "domCanvas": 2,
    "sourceCanvas": 0,
    "rfHits": 5,
    "scriptTags": 2,
    "rootLinks": 12
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "TRFMC v0.86E · Theory Spine",
    "url": "/trfmc_theory_spine_v86e.html",
    "file": "frontend/public/trfmc_theory_spine_v86e.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 5,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "Knowledge Base / Theory / Procedures Atlas",
    "url": "/trfmc_knowledge_base_theory_procedures_v1.html",
    "file": "frontend/public/trfmc_knowledge_base_theory_procedures_v1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 3,
    "scriptTags": 4,
    "rootLinks": 8
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "signal-dsp",
    "title": "Fiber / Fronthaul / OTDR Workbench",
    "url": "/trfmc_fiber_fronthaul_otdr_workbench_v1.html",
    "file": "frontend/public/trfmc_fiber_fronthaul_otdr_workbench_v1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 1,
    "scriptTags": 4,
    "rootLinks": 8
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC v0.40 Executive Mission Dashboard",
    "url": "/executive_mission_dashboard_v40.html",
    "file": "frontend/public/executive_mission_dashboard_v40.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 180,
    "scriptTags": 15,
    "rootLinks": 81
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC Instrument OS Alignment V1",
    "url": "/trfmc_instrument_os_alignment_v1.html",
    "file": "frontend/public/trfmc_instrument_os_alignment_v1.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 88,
    "scriptTags": 6,
    "rootLinks": 20
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC Perfection Authority V1",
    "url": "/trfmc_perfection_authority_v1.html",
    "file": "frontend/public/trfmc_perfection_authority_v1.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 87,
    "scriptTags": 3,
    "rootLinks": 148
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC Orphan Triage Board V1",
    "url": "/trfmc_orphan_triage_board_v1.html",
    "file": "frontend/public/trfmc_orphan_triage_board_v1.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 78,
    "scriptTags": 3,
    "rootLinks": 53
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC RF/TM War Room V4",
    "url": "/trfmc_rf_tm_war_room_v4.html",
    "file": "frontend/public/trfmc_rf_tm_war_room_v4.html",
    "domCanvas": 8,
    "sourceCanvas": 8,
    "rfHits": 68,
    "scriptTags": 6,
    "rootLinks": 17
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC Master Console V4",
    "url": "/trfmc_master_console_v4.html",
    "file": "frontend/public/trfmc_master_console_v4.html",
    "domCanvas": 2,
    "sourceCanvas": 2,
    "rfHits": 63,
    "scriptTags": 6,
    "rootLinks": 26
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC v0.70A Unified Shell · TRFMC v0.59A · Executive Dashboard Next Enterprise Production Layer",
    "url": "/executive_mission_dashboard_v_next.html",
    "file": "frontend/public/executive_mission_dashboard_v_next.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 59,
    "scriptTags": 7,
    "rootLinks": 40
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC Orphan Quarantine Room V1",
    "url": "/trfmc_orphan_quarantine_room_v1.html",
    "file": "frontend/public/trfmc_orphan_quarantine_room_v1.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 35,
    "scriptTags": 3,
    "rootLinks": 33
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC Safe Runtime Action Console V1",
    "url": "/trfmc_safe_runtime_action_console_v1.html",
    "file": "frontend/public/trfmc_safe_runtime_action_console_v1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 28,
    "scriptTags": 6,
    "rootLinks": 13
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC v0.86A · RF Physics Sapienza Console",
    "url": "/rf_physics_sapienza_console_v86a.html",
    "file": "frontend/public/rf_physics_sapienza_console_v86a.html",
    "domCanvas": 5,
    "sourceCanvas": 5,
    "rfHits": 27,
    "scriptTags": 6,
    "rootLinks": 11
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC RF PRO Signal Intelligence Lab V2",
    "url": "/trfmc_rf_pro_signal_intelligence_lab_v2.html",
    "file": "frontend/public/trfmc_rf_pro_signal_intelligence_lab_v2.html",
    "domCanvas": 9,
    "sourceCanvas": 0,
    "rfHits": 26,
    "scriptTags": 4,
    "rootLinks": 14
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC RF PRO Signal Intelligence Lab V3 Reality",
    "url": "/trfmc_rf_pro_signal_intelligence_lab_v3_reality.html",
    "file": "frontend/public/trfmc_rf_pro_signal_intelligence_lab_v3_reality.html",
    "domCanvas": 6,
    "sourceCanvas": 0,
    "rfHits": 26,
    "scriptTags": 5,
    "rootLinks": 14
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC RF PRO Signal Intelligence Lab V1",
    "url": "/trfmc_rf_pro_signal_intelligence_lab_v1.html",
    "file": "frontend/public/trfmc_rf_pro_signal_intelligence_lab_v1.html",
    "domCanvas": 8,
    "sourceCanvas": 0,
    "rfHits": 25,
    "scriptTags": 4,
    "rootLinks": 14
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC RF PRO Signal Intelligence Lab V4 Instrument",
    "url": "/trfmc_rf_pro_signal_intelligence_lab_v4_instrument.html",
    "file": "frontend/public/trfmc_rf_pro_signal_intelligence_lab_v4_instrument.html",
    "domCanvas": 6,
    "sourceCanvas": 0,
    "rfHits": 21,
    "scriptTags": 4,
    "rootLinks": 14
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "Cyber RF Intelligence / Evidence Lab",
    "url": "/trfmc_cyber_rf_intelligence_evidence_v1.html",
    "file": "frontend/public/trfmc_cyber_rf_intelligence_evidence_v1.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 17,
    "scriptTags": 4,
    "rootLinks": 8
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC v0.76A · RF/Telco Component Object Library",
    "url": "/rf_telco_component_library_v76.html",
    "file": "frontend/public/rf_telco_component_library_v76.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 12,
    "scriptTags": 7,
    "rootLinks": 8
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC v0.85A · Sapienza Master Template Doctrine",
    "url": "/sapienza_master_template_doctrine_v85a.html",
    "file": "frontend/public/sapienza_master_template_doctrine_v85a.html",
    "domCanvas": 0,
    "sourceCanvas": 0,
    "rfHits": 12,
    "scriptTags": 1,
    "rootLinks": 7
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC V5 Legacy Supervisor - Service Only",
    "url": "/trfmc_supervisor_mission_control_v5.html",
    "file": "frontend/public/trfmc_supervisor_mission_control_v5.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 11,
    "scriptTags": 5,
    "rootLinks": 12
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC Collaudo Portale 5173",
    "url": "/trfmc_collaudo_report.html",
    "file": "frontend/public/trfmc_collaudo_report.html",
    "domCanvas": 1,
    "sourceCanvas": 1,
    "rfHits": 8,
    "scriptTags": 5,
    "rootLinks": 6
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC Visual Asset Engine Lab V3",
    "url": "/trfmc_visual_asset_engine_lab_v3.html",
    "file": "frontend/public/trfmc_visual_asset_engine_lab_v3.html",
    "domCanvas": 9,
    "sourceCanvas": 0,
    "rfHits": 8,
    "scriptTags": 4,
    "rootLinks": 10
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "TRFMC Instrument Design System Lab V1",
    "url": "/trfmc_instrument_design_system_lab_v1.html",
    "file": "frontend/public/trfmc_instrument_design_system_lab_v1.html",
    "domCanvas": 2,
    "sourceCanvas": 0,
    "rfHits": 6,
    "scriptTags": 2,
    "rootLinks": 5
  },
  {
    "status": "ACTIVE_REAL_PAGE",
    "category": "war-room",
    "title": "Trfmc Official Safe Entrypoint V6",
    "url": "/trfmc_official_safe_entrypoint_v6.html",
    "file": "frontend/public/trfmc_official_safe_entrypoint_v6.html",
    "domCanvas": 0,
    "sourceCanvas": 1,
    "rfHits": 2,
    "scriptTags": 4,
    "rootLinks": 7
  }
]

export const workingPageCategories = Array.from(new Set(workingPages.map((page) => page.category))).sort()
export const workingPagesByCategory = (category: string) => workingPages.filter((page) => page.category === category)
export const topWorkingPages = [...workingPages].sort((a, b) => b.rfHits - a.rfHits).slice(0, 24)
